spring:
  datasource:
    name: counsel
    url: jdbc:mysql://localhost:3306/counsel #url
    username: counsel  #用户名
    password: counsel  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  flyway:
    enabled: true
    # 禁止清理数据库表
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: top.boywei.counsel.bean #配置实体类
